Feature shows on movie
Ehnwall/Filmvisarna pull request #60
Opened 2024-10-23 08:02 UTC by EricClasson

2024-10-23 09:30 UTC, BomanStatic requested changes

2024-10-23 09:30 UTC, BomanStatic commented on src/componets/onemovie/Shows.tsx
> +                                    <Card.Link className="btn btn-outline-primary mt-auto w-100" href="/booking-page">
Skulle denna link kunna länka till den faktiska booknings-sidan? alltså /boka-film/:showId?

2024-10-23 09:30 UTC, BomanStatic commented on src/pages/oneMoviePage/index.tsx
> +import Shows from '../../componets/onemovie/shows'
Borde vara ett stort "S" på shows i importen ../../componets/onemovie/shows

2024-10-23 09:30 UTC, BomanStatic commented on src/utils/api/movies/useGetMovies.ts
> +    console.log(data)
???

2024-10-23 09:57 UTC, EricClasson commented
fixed for merge @BomanStatic

2024-10-24 06:56 UTC, BomanStatic approved these changes

2024-10-25 06:52 UTC, merged